//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.29 at 02:30:03 ���� CST 
//


package com.xmltoobject.test.com.xmltoobject.test;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xmltoobject.test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Pattern_QNAME = new QName("http://www.kedou.com/exceptionProcessers/", "pattern");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xmltoobject.test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Excludes }
     * 
     */
    public Excludes createExcludes() {
        return new Excludes();
    }

    /**
     * Create an instance of {@link ExceptionProcessers }
     * 
     */
    public ExceptionProcessers createExceptionProcessers() {
        return new ExceptionProcessers();
    }

    /**
     * Create an instance of {@link Processer }
     * 
     */
    public Processer createProcesser() {
        return new Processer();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.kedou.com/exceptionProcessers/", name = "pattern")
    public JAXBElement<String> createPattern(String value) {
        return new JAXBElement<String>(_Pattern_QNAME, String.class, null, value);
    }

}
