//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.29 at 03:45:46 ���� CST 
//


package com.xmltoobject.test;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cacheEngines">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cacheEngine" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="engineName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="implClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="engineDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="params" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="param" type="{}Param" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CacheItems">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CacheItem" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="cacheName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="engineName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="cacheDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="params" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="param" type="{}Param" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cacheEngines",
    "cacheItems"
})
@XmlRootElement(name = "CacheManagerInfo")
public class CacheManagerInfo {

    @XmlElement(required = true)
    public CacheManagerInfo.CacheEngines cacheEngines;
    @XmlElement(name = "CacheItems", required = true)
	public CacheManagerInfo.CacheItems cacheItems;

    /**
     * Gets the value of the cacheEngines property.
     * 
     * @return
     *     possible object is
     *     {@link CacheManagerInfo.CacheEngines }
     *     
     */
    public CacheManagerInfo.CacheEngines getCacheEngines() {
        return cacheEngines;
    }

    /**
     * Sets the value of the cacheEngines property.
     * 
     * @param value
     *     allowed object is
     *     {@link CacheManagerInfo.CacheEngines }
     *     
     */
    public void setCacheEngines(CacheManagerInfo.CacheEngines value) {
        this.cacheEngines = value;
    }

    /**
     * Gets the value of the cacheItems property.
     * 
     * @return
     *     possible object is
     *     {@link CacheManagerInfo.CacheItems }
     *     
     */
    public CacheManagerInfo.CacheItems getCacheItems() {
        return cacheItems;
    }

    /**
     * Sets the value of the cacheItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link CacheManagerInfo.CacheItems }
     *     
     */
    public void setCacheItems(CacheManagerInfo.CacheItems value) {
        this.cacheItems = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cacheEngine" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="engineName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="implClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="engineDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="params" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="param" type="{}Param" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cacheEngine"
    })
    public static class CacheEngines {

        @XmlElement(required = true)
        public List<CacheManagerInfo.CacheEngines.CacheEngine> cacheEngine;

        /**
         * Gets the value of the cacheEngine property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cacheEngine property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCacheEngine().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CacheManagerInfo.CacheEngines.CacheEngine }
         * 
         * 
         */
        public List<CacheManagerInfo.CacheEngines.CacheEngine> getCacheEngine() {
            if (cacheEngine == null) {
                cacheEngine = new ArrayList<CacheManagerInfo.CacheEngines.CacheEngine>();
            }
            return this.cacheEngine;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="engineName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="implClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="engineDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="params" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="param" type="{}Param" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "engineName",
            "implClass",
            "engineDesc",
            "params"
        })
        public static class CacheEngine {

            @XmlElement(required = true)
            public String engineName;
            @XmlElement(required = true)
            public String implClass;
            @XmlElement(required = true)
            public String engineDesc;
            public CacheManagerInfo.CacheEngines.CacheEngine.Params params;

            /**
             * Gets the value of the engineName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEngineName() {
                return engineName;
            }

            /**
             * Sets the value of the engineName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEngineName(String value) {
                this.engineName = value;
            }

            /**
             * Gets the value of the implClass property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImplClass() {
                return implClass;
            }

            /**
             * Sets the value of the implClass property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImplClass(String value) {
                this.implClass = value;
            }

            /**
             * Gets the value of the engineDesc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEngineDesc() {
                return engineDesc;
            }

            /**
             * Sets the value of the engineDesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEngineDesc(String value) {
                this.engineDesc = value;
            }

            /**
             * Gets the value of the params property.
             * 
             * @return
             *     possible object is
             *     {@link CacheManagerInfo.CacheEngines.CacheEngine.Params }
             *     
             */
            public CacheManagerInfo.CacheEngines.CacheEngine.Params getParams() {
                return params;
            }

            /**
             * Sets the value of the params property.
             * 
             * @param value
             *     allowed object is
             *     {@link CacheManagerInfo.CacheEngines.CacheEngine.Params }
             *     
             */
            public void setParams(CacheManagerInfo.CacheEngines.CacheEngine.Params value) {
                this.params = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="param" type="{}Param" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "param"
            })
            public static class Params {

                public List<Param> param;

                /**
                 * Gets the value of the param property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the param property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getParam().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Param }
                 * 
                 * 
                 */
                public List<Param> getParam() {
                    if (param == null) {
                        param = new ArrayList<Param>();
                    }
                    return this.param;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CacheItem" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="cacheName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="engineName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cacheDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="params" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="param" type="{}Param" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cacheItem"
    })
    public static class CacheItems {

        @XmlElement(name = "CacheItem")
        public List<CacheManagerInfo.CacheItems.CacheItem> cacheItem;

        /**
         * Gets the value of the cacheItem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cacheItem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCacheItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CacheManagerInfo.CacheItems.CacheItem }
         * 
         * 
         */
        public List<CacheManagerInfo.CacheItems.CacheItem> getCacheItem() {
            if (cacheItem == null) {
                cacheItem = new ArrayList<CacheManagerInfo.CacheItems.CacheItem>();
            }
            return this.cacheItem;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="cacheName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="engineName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cacheDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="params" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="param" type="{}Param" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cacheName",
            "engineName",
            "cacheDesc",
            "params"
        })
        public static class CacheItem {

            @XmlElement(required = true)
            public String cacheName;
            @XmlElement(required = true)
            public String engineName;
            @XmlElement(required = true)
            public String cacheDesc;
            public CacheManagerInfo.CacheItems.CacheItem.Params params;

            /**
             * Gets the value of the cacheName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCacheName() {
                return cacheName;
            }

            /**
             * Sets the value of the cacheName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCacheName(String value) {
                this.cacheName = value;
            }

            /**
             * Gets the value of the engineName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEngineName() {
                return engineName;
            }

            /**
             * Sets the value of the engineName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEngineName(String value) {
                this.engineName = value;
            }

            /**
             * Gets the value of the cacheDesc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCacheDesc() {
                return cacheDesc;
            }

            /**
             * Sets the value of the cacheDesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCacheDesc(String value) {
                this.cacheDesc = value;
            }

            /**
             * Gets the value of the params property.
             * 
             * @return
             *     possible object is
             *     {@link CacheManagerInfo.CacheItems.CacheItem.Params }
             *     
             */
            public CacheManagerInfo.CacheItems.CacheItem.Params getParams() {
                return params;
            }

            /**
             * Sets the value of the params property.
             * 
             * @param value
             *     allowed object is
             *     {@link CacheManagerInfo.CacheItems.CacheItem.Params }
             *     
             */
            public void setParams(CacheManagerInfo.CacheItems.CacheItem.Params value) {
                this.params = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="param" type="{}Param" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "param"
            })
            public static class Params {

                public List<Param> param;

                /**
                 * Gets the value of the param property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the param property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getParam().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Param }
                 * 
                 * 
                 */
                public List<Param> getParam() {
                    if (param == null) {
                        param = new ArrayList<Param>();
                    }
                    return this.param;
                }

            }

        }

    }

}
