//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.29 at 03:45:46 ÏÂÎç CST 
//


package com.xmltoobject.test;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xmltoobject.test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xmltoobject.test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CacheManagerInfo.CacheEngines.CacheEngine }
     * 
     */
    public CacheManagerInfo.CacheEngines.CacheEngine createCacheManagerInfoCacheEnginesCacheEngine() {
        return new CacheManagerInfo.CacheEngines.CacheEngine();
    }

    /**
     * Create an instance of {@link CacheManagerInfo.CacheEngines }
     * 
     */
    public CacheManagerInfo.CacheEngines createCacheManagerInfoCacheEngines() {
        return new CacheManagerInfo.CacheEngines();
    }

    /**
     * Create an instance of {@link CacheManagerInfo.CacheItems.CacheItem.Params }
     * 
     */
    public CacheManagerInfo.CacheItems.CacheItem.Params createCacheManagerInfoCacheItemsCacheItemParams() {
        return new CacheManagerInfo.CacheItems.CacheItem.Params();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link CacheManagerInfo.CacheItems.CacheItem }
     * 
     */
    public CacheManagerInfo.CacheItems.CacheItem createCacheManagerInfoCacheItemsCacheItem() {
        return new CacheManagerInfo.CacheItems.CacheItem();
    }

    /**
     * Create an instance of {@link CacheManagerInfo.CacheItems }
     * 
     */
    public CacheManagerInfo.CacheItems createCacheManagerInfoCacheItems() {
        return new CacheManagerInfo.CacheItems();
    }

    /**
     * Create an instance of {@link CacheManagerInfo }
     * 
     */
    public CacheManagerInfo createCacheManagerInfo() {
        return new CacheManagerInfo();
    }

    /**
     * Create an instance of {@link CacheManagerInfo.CacheEngines.CacheEngine.Params }
     * 
     */
    public CacheManagerInfo.CacheEngines.CacheEngine.Params createCacheManagerInfoCacheEnginesCacheEngineParams() {
        return new CacheManagerInfo.CacheEngines.CacheEngine.Params();
    }

}
